Polish init script

diff --git a/init b/init
--- a/init
+++ b/init
@@ -10,7 +10,7 @@ function print_help () {
     echo -e "Check for missing packages and setup the project.\n"
     echo "Optional arguments:"
     echo -e "  -h\tdisplay this help and exit"
-    echo -e "  --without-lib-setup\tskip the step for setting up libs"
+    echo -e "  --without-libs-setup\tskip the step for setting up libs"
     echo -e "  --wsl-quicklisp-proxy \"host:port\"\tquicklist HTTP proxy (this flag + HTTP proxy are required on WSL)"
 }
 
@@ -34,7 +34,7 @@ function setup_virtualenv () {
 
 wsl_quicklisp_proxy=""
 setup_libs=true
-if [[ $# -eq 1 ]] && [[ "$1" == "-h" ]]; then
+if [[ $# -eq 1 && "$1" == "-h" ]]; then
     print_help
     exit 0
 else
@@ -42,10 +42,15 @@ else
         case "$1" in
           --wsl-quicklisp-proxy)
               shift
+              if [[ $# -eq 0 ]]; then
+                  echo "Missing proxy URL"
+                  print_help
+                  exit 1
+              fi
               wsl_quicklisp_proxy=":proxy \"http://$1/\""
               shift
           ;;
-          --without-lib-setup)
+          --without-libs-setup)
               shift
               setup_libs=false
           ;;
