added git_ref

diff --git a/tests/mgbench/Dockerfile.mgbench_full b/tests/mgbench/Dockerfile.mgbench_full
--- a/tests/mgbench/Dockerfile.mgbench_full
+++ b/tests/mgbench/Dockerfile.mgbench_full
@@ -16,11 +16,16 @@ RUN wget -q https://s3-eu-west-1.amazonaws.com/deps.memgraph.io/${TOOLCHAIN_VERS
     -O ${TOOLCHAIN_VERSION}-binaries-ubuntu-24.04-${TARGETARCH}.tar.gz \
     && tar xzvf ${TOOLCHAIN_VERSION}-binaries-ubuntu-24.04-${TARGETARCH}.tar.gz -C /opt
 
-RUN git clone https://github.com/memgraph/memgraph.git && \
+    RUN set -eux; \
     if [ -n "${GIT_REF}" ]; then \
-        cd memgraph && \
-        git checkout "${GIT_REF}" \
-        cd .. \
+      echo "Checking out ${GIT_REF}"; \
+      cd /opt/memgraph && \
+      git fetch --all --tags && \
+      git rev-parse --verify --quiet "${GIT_REF}" \
+        && git checkout "${GIT_REF}" \
+        || (echo "Ref '${GIT_REF}' not found" >&2; exit 1); \
+    else \
+      echo "No GIT_REF provided; staying on default branch"; \
     fi
 
 WORKDIR memgraph
