Add workflow which checks Diff for flakiness (#2199)
This PR develops and adds a workflow which checks the Diff workflow for
flakiness.
It works in 2 modes:
- Every job can now be run multiple times on workflow dispatch
- Nightly flakiness testing of the entire test suite

diff --git a/.github/workflows/check_flakiness.yaml b/.github/workflows/check_flakiness.yaml
--- a/.github/workflows/check_flakiness.yaml
+++ b/.github/workflows/check_flakiness.yaml
@@ -1,6 +1,11 @@
 name: "Check Diff for flakiness"
+concurrency:
+  group: ${{ github.head_ref }}-${{ github.sha }}
+  cancel-in-progress: true
 
 on:
+  schedule:
+    - cron: "0 1 * * *" #UTC
   workflow_dispatch:
     inputs:
       community_core:
@@ -31,50 +36,130 @@ on:
         type: boolean
         default: true
       flakiness_runs:
-        type: string
-        description: "Change this to check for flakiness by running every selected job multiple times. Enter a number between 2 and 20."
+        type: number
+        default: 3
+        required: true
+        description: "Check for flakiness by running every selected job multiple times. Enter a number between 2 and 20."
 
 jobs:
   DiffSetup:
     runs-on: ubuntu-latest
     outputs:
+      run_community_core: ${{ steps.setup.outputs.run_community_core }}
+      run_coverage_core: ${{ steps.setup.outputs.run_coverage_core }}
+      run_debug_core: ${{ steps.setup.outputs.run_debug_core }}
+      run_debug_integration: ${{ steps.setup.outputs.run_debug_integration }}
+      run_jepsen_core: ${{ steps.setup.outputs.run_jepsen_core }}
+      run_release_core: ${{ steps.setup.outputs.run_release_core }}
+      run_release_benchmark: ${{ steps.setup.outputs.run_release_benchmark}}
+      run_release_e2e: ${{ steps.setup.outputs.run_release_e2e }}
+      run_release_stress: ${{ steps.setup.outputs.run_release_stress }}
       runs: ${{ steps.setup_flakiness.outputs.runs }}
+    env:
+      GH_CONTEXT: ${{ toJson(github) }}
+      GH_CONTEXT_FILE_NAME: github_context.json
+      FLAKINESS_RUNS: ${{ github.event.inputs.flakiness_runs || 10 }}
     steps:
+      - name: Set up repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: Dump GitHub context
+        run: echo "$GH_CONTEXT" >> "$GH_CONTEXT_FILE_NAME"
+      - name: Set up diff execution
+        id: setup
+        run: ./tools/diff_setup.py --gh-context-path "$GH_CONTEXT_FILE_NAME" --base-branch "origin/master"
       - name: Set up flakiness runs
         id: setup_flakiness
         run: |
-          flakiness_runs=1
-          if [[ -n "${{ github.event.inputs.flakiness_runs }}" ]]; then
-            echo "Debug 1"
-            if [[ "${{ github.event.inputs.flakiness_runs }}" -ge 2 ]] && [[ "${{ github.event.inputs.flakiness_runs }}" -le 20 ]]; then
-              echo "Debug 2"
-              flakiness_runs=${{ github.event.inputs.flakiness_runs }}
-            else
-              echo "ERROR: Selected 'flakiness_runs' value is invalid. Please select a value between 2 and 20."
-            fi
+          if [[ $FLAKINESS_RUNS -lt 2 ]] || [[ $FLAKINESS_RUNS -gt 20 ]]; then
+            echo "ERROR: Selected 'flakiness_runs' value is invalid. Please select a value between 2 and 20."
+            exit 1
           fi
           sequence=""
-          for i in $(seq 1 $flakiness_runs); do
+          for i in $(seq 1 $FLAKINESS_RUNS); do
             sequence+="${i},"
           done
           echo "runs=[${sequence::-1}]" >> $GITHUB_OUTPUT
 
-  Diff:
+  Community:
     needs: DiffSetup
     strategy:
       fail-fast: false
       max-parallel: 3
       matrix:
         run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
-    uses: ./.github/workflows/diff.yaml
+    uses: ./.github/workflows/diff_community.yaml
     with:
-      community_core: "${{ github.event.inputs.community_core }}"
-      coverage_core: "${{ github.event.inputs.coverage_core }}"
-      debug_core: "${{ github.event.inputs.debug_core }}"
-      debug_integration: "${{ github.event.inputs.debug_integration }}"
-      jepsen_core: "${{ github.event.inputs.jepsen_core }}"
-      release_core: "${{ github.event.inputs.release_core }}"
-      release_benchmark: "${{ github.event.inputs.release_benchmark }}"
-      release_e2e: "${{ github.event.inputs.release_e2e }}"
-      release_stress: "${{ github.event.inputs.release_stress }}"
+      arch: 'amd'
+      os: 'debian-11'
+      toolchain: 'v5'
+      run_core: ${{ needs.DiffSetup.outputs.run_community_core }}
+      run_id: "${{ matrix.run_no }}"
+    secrets: inherit
+
+  Coverage:
+    needs: DiffSetup
+    strategy:
+      fail-fast: false
+      max-parallel: 3
+      matrix:
+        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
+    uses: ./.github/workflows/diff_coverage.yaml
+    with:
+      arch: 'amd'
+      os: 'debian-11'
+      toolchain: 'v5'
+      run_core: ${{ needs.DiffSetup.outputs.run_coverage_core }}
+      run_clang_tidy: ${{ needs.DiffSetup.outputs.run_coverage_core }}
+      run_id: "${{ matrix.run_no }}"
+    secrets: inherit
+
+  Debug:
+    needs: DiffSetup
+    strategy:
+      fail-fast: false
+      max-parallel: 3
+      matrix:
+        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
+    uses: ./.github/workflows/diff_debug.yaml
+    with:
+      arch: 'amd'
+      os: 'debian-11'
+      toolchain: 'v5'
+      run_core: ${{ needs.DiffSetup.outputs.run_debug_core }}
+      run_integration: ${{ needs.DiffSetup.outputs.run_debug_integration }}
+      run_id: "${{ matrix.run_no }}"
+    secrets: inherit
+
+  Jepsen:
+    needs: DiffSetup
+    strategy:
+      fail-fast: false
+      max-parallel: 3
+      matrix:
+        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
+    uses: ./.github/workflows/diff_jepsen.yaml
+    with:
+      run_core: ${{ needs.DiffSetup.outputs.run_jepsen_core }}
+      run_id: "${{ matrix.run_no }}"
+    secrets: inherit
+
+  Release:
+    needs: DiffSetup
+    strategy:
+      fail-fast: false
+      max-parallel: 3
+      matrix:
+        run_no: ${{ fromJSON(needs.DiffSetup.outputs.runs) }}
+    uses: ./.github/workflows/diff_release.yaml
+    with:
+      arch: 'amd'
+      os: 'debian-11'
+      toolchain: 'v5'
+      run_core: ${{ needs.DiffSetup.outputs.run_release_core }}
+      run_benchmark: ${{ needs.DiffSetup.outputs.run_release_benchmark }}
+      run_e2e: ${{ needs.DiffSetup.outputs.run_release_e2e }}
+      run_stress: ${{ needs.DiffSetup.outputs.run_release_stress }}
+      run_id: "${{ matrix.run_no }}"
     secrets: inherit
