remove workflow code to copy builds

diff --git a/.github/workflows/promote_daily_rc.yml b/.github/workflows/promote_daily_rc.yml
--- a/.github/workflows/promote_daily_rc.yml
+++ b/.github/workflows/promote_daily_rc.yml
@@ -22,9 +22,9 @@ on:
         type: boolean
         description: "Override existing RC"
         default: false
-      overwrite_branch:
+      overwrite:
         type: boolean
-        description: "Delete existing release branch, if found"
+        description: "Delete existing release branch and tag, if found"
         default: false
 
 env:
@@ -62,14 +62,46 @@ jobs:
         run: |
           # command here to figure out commit hash to checkout for release
           commit_hash="$(python3 tools/get_daily_commit_hash.py date)"
+          
+          # Count the number of words (hashes) in the result
+          num_hashes=$(echo "$commit_hash" | wc -w)
+
+          if [ -z "$commit_hash" ] || [ "$num_hashes" -ne 1 ]; then
+            echo "Error: commit_hash is either empty or has multiple hash values."
+            echo "Hashes found: $commit_hash"
+            exit 1
+          fi
+
+          echo "Using commit hash: $commit_hash"
           echo "COMMIT_HASH=$commit_hash" >> $GITHUB_ENV
 
       - name: Checkout Release Branch and Create Tag
         run: |
+          # delete tag if it already exists
+          tag_name="v${{ inputs.release_version }}-${{ inputs.rc_version }}"
+          # Check if the tag exists locally
+          if git show-ref --tags "$tag_name" > /dev/null 2>&1; then
+            echo "Tag '$tag_name' exists in this repository."
+            
+            if [ "${{ inputs.overwrite }}" = true ]; then
+              echo "Overwrite flag is true, deleting tag '$tag_name' locally and on remote 'origin'."
+              # Delete the local tag
+              git tag -d "$tag_name"
+              
+              # Delete the tag from the remote called 'origin'
+              git push origin --delete "$tag_name"
+            else
+              echo "Overwrite flag is false. Exiting with error as tag '$tag_name' already exists."
+              exit 1
+            fi
+          else
+            echo "Tag '$tag_name' does not exist. No action taken."
+          fi
+
           # delete the release branch if it already exists (I don't like this, a better way should probably be found)
           branch_name="release/v${{ inputs.release_version }}"
           if git ls-remote --exit-code --heads origin "$branch_name"; then
-            if [ "${{ inputs.overwrite_branch }}" == "true" ]; then
+            if [ "${{ inputs.overwrite }}" == "true" ]; then
               echo "Branch '$branch_name' exists, deleting it..."
               git push origin --delete "$branch_name"
             else
@@ -89,95 +121,14 @@ jobs:
           # override memgraph version
           sed -i "s/set(MEMGRAPH_OVERRIDE_VERSION \"\")/set(MEMGRAPH_OVERRIDE_VERSION \"${{ inputs.release_version }}\")/" CMakeLists.txt
           git add CMakeLists.txt
-          git commit -m "Update CMakeLists.txt with new memgraph override version [skip package]"
+          git commit -m "Update CMakeLists.txt with new memgraph override version [skip tests]"
 
           # push to github
           git push --set-upstream origin $branch_name
 
           # add tag
-          tag_name="v${{ inputs.release_version }}-${{ inputs.rc_version }}"
           git tag $tag_name
 
           # push tag to github
           git push && git push origin $tag_name
-
-
-          
-  PromotePackage:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [centos-9, centos-10, debian-11, debian-12, docker, fedora-41, ubuntu-22.04, ubuntu-24.04]
-        arch: [amd]
-        malloc: [false]
-        relwithdebinfo: [false]
-        include:
-          - os: docker
-            arch: arm
-            malloc: false
-            relwithdebinfo: false
-          - os: ubuntu-24.04
-            arch: arm
-            malloc: false
-            relwithdebinfo: false
-          - os: ubuntu-24.04
-            arch: amd
-            malloc: true
-            relwithdebinfo: false
-    steps:
-      - name: Set up repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Setup AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_AK_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SAK }}
-          aws-region: ${{ env.s3_region }}
-
-      - name: Check Package Exists
-        run: |
-          read exists old_key new_key < <(python3 tools/check_s3_daily_release.py ${{ inputs.release_date }} ${{ inputs.release_version }} ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.malloc }} ${{ matrix.relwithdebinfo }})
-          echo "OLD_KEY=$old_key" >> $GITHUB_ENV
-          echo "NEW_KEY=$new_key" >> $GITHUB_ENV
-
-      - name: Copy Package
-        run: |
-          aws s3 cp s3://${rc_bucket}/${{ env.OLD_KEY }} s3://${rc_bucket}/${{ env.NEW_KEY }}
-
-
-  PromoteDocker:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [docker]
-        build_type: [Release, RelWithDebInfo]
-    steps:
-      - name: Set up repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Setup AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_AK_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SAK }}
-          aws-region: ${{ env.s3_region }}
-
-      - name: Check Package Exists
-        run: |
-          read exists old_key new_key < <(python3 tools/check_s3_daily_release.py ${{ inputs.release_date }} ${{ inputs.release_version }} ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.malloc }} ${{ matrix.relwithdebinfo }})
-          echo "OLD_KEY=$old_key" >> $GITHUB_ENV
-          echo "NEW_KEY=$new_key" >> $GITHUB_ENV
-
-      - name: Copy Package
-        run: |
-          aws s3 cp s3://${rc_bucket}/${{ env.OLD_KEY }} s3://${rc_bucket}/${{ env.NEW_KEY }}
-
-    
 
