Add jobs to create and store rc artifacts

diff --git a/.github/workflows/reusable_package.yaml b/.github/workflows/reusable_package.yaml
--- a/.github/workflows/reusable_package.yaml
+++ b/.github/workflows/reusable_package.yaml
@@ -6,29 +6,25 @@ on:
       os:
         type: string
         description: "Target os. Default value is debian-12."
-        default: 'debian-12'
+        default: debian-12
       arch:
         type: string
         description: "Target architecture. Default value is amd."
-        default: 'amd'
+        default: amd
       toolchain:
         type: string
         description: "Toolchain version. Default value is v5."
-        default: 'v5'
+        default: v5
       build_type:
         type: string
         description: "Memgraph Build type. Default value is Release."
-        default: 'Release'
-      artifact_name:
-        type: string
-        description: "Unique artifact name, pass it in to override the default artifact name setting."
-        default: ''
+        default: Release
       additional_build_args:
         type: string
         description: "Additional build flags (--for-platform, --for-docker ...). Default value is empty."
         default: ''
       push_to_s3:
-        type: string 
+        type: string
         description: "Should the final package be pushed to an S3 bucket. Default value is false"
         default: false
       s3_bucket:
@@ -38,7 +34,7 @@ on:
       s3_region:
         type: string
         description: "Region for the target S3 bucket."
-        default: 'eu-west-1'
+        default: eu-west-1
       s3_dest_dir:
         type: string
         description: "Target dir path in S3 bucket."
@@ -68,21 +64,19 @@ jobs:
 
       - name: "Set artifact name and dir"
         run: |
-          if [[ -z "${{ inputs.artifact_name }}" ]]; then
-            if [[ "${{ inputs.additional_build_args }}" == *"--for-docker" ]]; then
-              artifact_name='docker'
-              echo "FOR_DOCKER=true" >> $GITHUB_ENV
-            elif [[ "${{ inputs.additional_build_args }}" == *"--for-platform" ]]; then
-              artifact_name="${{ inputs.os }}-platform"
-            else
-              artifact_name=${{ inputs.os }}
-              artifact_name=${artifact_name%*-arm}
-            fi
-            if [[ "${{ inputs.arch }}" == 'arm' ]]; then
-              artifact_name="${artifact_name}-aarch64"
-            fi
-          else
-            artifact_name=${{ inputs.artifact_name }}
+          artifact_name=${{ inputs.os }}
+          if [[ "${{ inputs.additional_build_args }}" == *"--for-docker" ]]; then
+            artifact_name='docker'
+            echo "FOR_DOCKER=true" >> $GITHUB_ENV
+          fi
+          if [[ "${{ inputs.additional_build_args }}" == *"--for-platform" ]]; then
+            artifact_name="${artifact_name}-platform"
+          fi
+          if [[ "${{ inputs.arch }}" == 'arm' ]]; then
+            artifact_name="${artifact_name}-aarch64"
+          fi
+          if [[ "${{ inputs.build_type }}" == 'RelWithDebInfo' ]]; then
+            artifact_name="${artifact_name}-relwithdebinfo"
           fi
           echo "ARTIFACT_NAME=$artifact_name" >> $GITHUB_ENV
           echo "ARTIFACT_DIR=build/output/$artifact_name" >> $GITHUB_ENV
@@ -166,38 +160,42 @@ jobs:
       - name: Validate dest_dir
         if: ${{ inputs.s3_bucket == 'download.memgraph.com' }}
         run: |
+          if [[ "${{ inputs.build_type }}" == 'RelWithDebInfo' ]]; then
+            echo -e "Error: You are pushing a RelWithDebInfo build to 'download.memgraph.com'."
+            exit 1
+          fi
           if ! [[ "${{ inputs.s3_dest_dir }}" =~ memgraph/v[0-9]\.[0-9]+\.[0-9]+$ ]]; then
             echo -e "Error: ${{ inputs.s3_dest_dir }} is not a valid official format. When pushing to 'download.memgraph.com' the dest dir has to match format 'memgraph/vX.Y.Z'!"
             exit 1
-          else
-            echo -e "Passed: Dest dir ${{ inputs.s3_dest_dir }} has a valid official format."
           fi
+          echo -e "Passed: Dest dir ${{ inputs.s3_dest_dir }} has a valid official format."
 
       - name: "Set artifact name"
         run: |
-          if [[ -z "${{ inputs.artifact_name }}" ]]; then
-            if [[ "${{ inputs.additional_build_args }}" == *"--for-docker" ]]; then
-              artifact_name='docker'
-              echo "FOR_DOCKER=true" >> $GITHUB_ENV
-            elif [[ "${{ inputs.additional_build_args }}" == *"--for-platform" ]]; then
-              artifact_name="${{ inputs.os }}-platform"
-            else
-              artifact_name=${{ inputs.os }}
-              artifact_name=${artifact_name%*-arm}
-            fi
-            if [[ "${{ inputs.arch }}" == 'arm' ]]; then
-              artifact_name="${artifact_name}-aarch64"
-            fi
-          else
-            artifact_name=${{ inputs.artifact_name }}
+          artifact_name=${{ inputs.os }}
+          artifact_dir="build/output/release"
+          if [[ "${{ inputs.additional_build_args }}" == *"--for-docker" ]]; then
+            artifact_name='docker'
+            echo "FOR_DOCKER=true" >> $GITHUB_ENV
+          fi
+          if [[ "${{ inputs.additional_build_args }}" == *"--for-platform" ]]; then
+            artifact_name="${artifact_name}-platform"
+          fi
+          if [[ "${{ inputs.arch }}" == 'arm' ]]; then
+            artifact_name="${artifact_name}-aarch64"
+          fi
+          if [[ "${{ inputs.build_type }}" == 'RelWithDebInfo' ]]; then
+            artifact_name="${artifact_name}-relwithdebinfo"
+            artifact_dir="build/output/relwithdebinfo"
           fi
           echo "ARTIFACT_NAME=$artifact_name" >> $GITHUB_ENV
+          echo "ARTIFACT_DIR=$artifact_dir" >> $GITHUB_ENV
 
       - name: Download artifacts
         uses: actions/download-artifact@v4
         with:
           name: ${{ env.ARTIFACT_NAME }}
-          path: "build/output/release"
+          path: ${{ env.ARTIFACT_DIR }}
 
       - name: Upload to S3
         uses: jakejarvis/s3-sync-action@v0.5.1
@@ -206,5 +204,5 @@ jobs:
           AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: ${{ inputs.s3_region }}
-          SOURCE_DIR: "build/output/release"
+          SOURCE_DIR: ${{ env.ARTIFACT_DIR }}
           DEST_DIR: "${{ inputs.s3_dest_dir }}/${{ env.ARTIFACT_NAME }}/"
