use env vars for inputs

diff --git a/.github/workflows/reusable_package.yaml b/.github/workflows/reusable_package.yaml
--- a/.github/workflows/reusable_package.yaml
+++ b/.github/workflows/reusable_package.yaml
@@ -51,6 +51,16 @@ on:
 env:
   TOOLCHAIN: v7
   GENERATE_SBOM: ${{ inputs.generate_sbom }}
+  ARCH: ${{ inputs.arch }}
+  BUILD_TYPE: ${{ inputs.build_type }}
+  OS: ${{ inputs.os }}
+  ADDITIONAL_BUILD_ARGS: ${{ inputs.additional_build_args }}
+  PUSH_TO_GITHUB: ${{ inputs.push_to_github }}
+  PUSH_TO_S3: ${{ inputs.push_to_s3 }}
+  S3_BUCKET: ${{ inputs.s3_bucket }}
+  S3_REGION: ${{ inputs.s3_region }}
+  S3_DEST_DIR: ${{ inputs.s3_dest_dir }}
+  REF: ${{ inputs.ref }}
 
 jobs:
   PackageAndUpload:
@@ -63,26 +73,21 @@ jobs:
       - name: "Validate S3 dest dir for official package"
         if: ${{ inputs.push_to_s3 == 'true' && inputs.s3_bucket == 'download.memgraph.com' }}
         run: |
-          if [[ "${{ inputs.build_type }}" == 'RelWithDebInfo' ]]; then
+          if [[ "$BUILD_TYPE" == 'RelWithDebInfo' ]]; then
             echo -e "Error: You are pushing a RelWithDebInfo build to 'download.memgraph.com'."
             exit 1
           fi
-          if ! [[ "${{ inputs.s3_dest_dir }}" =~ memgraph/v[0-9]\.[0-9]+\.[0-9]+$ ]]; then
-            echo -e "Error: ${{ inputs.s3_dest_dir }} is not a valid official format. When pushing to 'download.memgraph.com' the dest dir has to match format 'memgraph/vX.Y.Z'!"
+          if ! [[ "$S3_DEST_DIR" =~ memgraph/v[0-9]\.[0-9]+\.[0-9]+$ ]]; then
+            echo -e "Error: $S3_DEST_DIR is not a valid official format. When pushing to 'download.memgraph.com' the dest dir has to match format 'memgraph/vX.Y.Z'!"
             exit 1
           fi
-          echo -e "Passed: Dest dir ${{ inputs.s3_dest_dir }} has a valid official format."
+          echo -e "Passed: Dest dir $S3_DEST_DIR has a valid official format."
 
       - name: "Set up repository"
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 # Required because of release/get_version.py
           ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}
-
-      - name: "Unlock keychain for current session" # Required beacuse ARM builds run on macos
-        # if: ${{ inputs.arch == 'arm' }}
-        if: false
-        run: security -v unlock-keychain -p ${{ secrets.SELF_HOSTED_RUNNER_PASSWORD }} ~/Library/Keychains/login.keychain-db
 
       - name: "Log in to Docker Hub"
         uses: ./.github/actions/docker-login
@@ -94,18 +99,18 @@ jobs:
         run: |
           artifact_name="$INPUT_OS"
           artifact_dir='build/output'
-          if [[ "${{ inputs.additional_build_args }}" == *"--for-docker"* ]]; then
+          if [[ "$ADDITIONAL_BUILD_ARGS" == *"--for-docker"* ]]; then
             artifact_name='docker'
             echo "FOR_DOCKER=true" >> $GITHUB_ENV
             echo "DOCKER_ARTIFACT_DIR=${artifact_dir}/docker" >> $GITHUB_ENV
           fi
-          if [[ "${{ inputs.additional_build_args }}" == *"--disable-jemalloc"* ]]; then
+          if [[ "$ADDITIONAL_BUILD_ARGS" == *"--disable-jemalloc"* ]]; then
             artifact_name="${artifact_name}-malloc"
           fi
-          if [[ "${{ inputs.arch }}" == 'arm' ]]; then
+          if [[ "$ARCH" == 'arm' ]]; then
             artifact_name="${artifact_name}-aarch64"
           fi
-          if [[ "${{ inputs.build_type }}" == 'RelWithDebInfo' ]]; then
+          if [[ "$BUILD_TYPE" == 'RelWithDebInfo' ]]; then
             artifact_name="${artifact_name}-relwithdebinfo"
           fi
           echo "ARTIFACT_NAME=$artifact_name" >> $GITHUB_ENV
@@ -113,7 +118,7 @@ jobs:
 
       - name: Set Additional Build Args
         run: |
-          args="${{ inputs.additional_build_args }} --disable-testing"
+          args="$ADDITIONAL_BUILD_ARGS --disable-testing"
           echo "ADDITIONAL_BUILD_ARGS=$args" >> $GITHUB_ENV
           echo "Final build args: $args"
 
@@ -122,7 +127,7 @@ jobs:
           ./release/package/mgbuild.sh \
           --toolchain $TOOLCHAIN \
           --os "$INPUT_OS" \
-          --arch ${{ inputs.arch }} \
+          --arch $ARCH \
           run
 
       - name: "Build Memgraph binaries"
@@ -130,18 +135,18 @@ jobs:
           ./release/package/mgbuild.sh \
           --toolchain $TOOLCHAIN \
           --os "$INPUT_OS" \
-          --arch ${{ inputs.arch }} \
-          --build-type ${{ inputs.build_type }} \
-          --mgdeps-cache-host ${{ env.mgdeps_cache_host }} \
-          build-memgraph ${{ env.ADDITIONAL_BUILD_ARGS }}
+          --arch $ARCH \
+          --build-type $BUILD_TYPE \
+          --mgdeps-cache-host $MGDEPS_CACHE_HOST \
+          build-memgraph $ADDITIONAL_BUILD_ARGS
 
       - name: "Make package"
         run: |
           ./release/package/mgbuild.sh \
           --toolchain $TOOLCHAIN \
           --os "$INPUT_OS" \
-          --arch ${{ inputs.arch }} \
-          --build-type ${{ inputs.build_type }} \
+          --arch $ARCH \
+          --build-type $BUILD_TYPE \
           package-memgraph
 
       - name: "Copy package"
@@ -149,10 +154,10 @@ jobs:
           ./release/package/mgbuild.sh \
           --toolchain $TOOLCHAIN \
           --os "$INPUT_OS" \
-          --arch ${{ inputs.arch }} \
+          --arch $ARCH \
           copy \
           --package \
-          --dest-dir ${{ env.PACKAGE_ARTIFACT_DIR }}
+          --dest-dir $PACKAGE_ARTIFACT_DIR
 
       - name: "Copy SBOM"
         if: ${{ env.GENERATE_SBOM == 'true' }}
@@ -160,7 +165,7 @@ jobs:
           ./release/package/mgbuild.sh \
           --toolchain $TOOLCHAIN \
           --os "$INPUT_OS" \
-          --arch ${{ inputs.arch }} \
+          --arch $ARCH \
           copy \
           --sbom
 
@@ -170,7 +175,7 @@ jobs:
           ./release/package/mgbuild.sh \
           --toolchain $TOOLCHAIN \
           --os "$INPUT_OS" \
-          --arch ${{ inputs.arch }} \
+          --arch $ARCH \
           build-heaptrack
 
       - name: "Copy heaptrack"
@@ -180,7 +185,7 @@ jobs:
           ./release/package/mgbuild.sh \
           --toolchain $TOOLCHAIN \
           --os "$INPUT_OS" \
-          --arch ${{ inputs.arch }} \
+          --arch $ARCH \
           copy-heaptrack \
           --dest-dir "$(pwd)/release/docker"
 
@@ -190,7 +195,7 @@ jobs:
           ./release/package/mgbuild.sh \
           --toolchain $TOOLCHAIN \
           --os "$INPUT_OS" \
-          --arch ${{ inputs.arch }} \
+          --arch $ARCH \
           stop --remove
 
       - name: "Create docker image"
@@ -199,15 +204,15 @@ jobs:
           ./release/package/mgbuild.sh \
           --toolchain $TOOLCHAIN \
           --os "$INPUT_OS" \
-          --arch ${{ inputs.arch }} \
-          --build-type ${{ inputs.build_type }} \
+          --arch $ARCH \
+          --build-type $BUILD_TYPE \
           package-docker \
-          --src-dir ${{ env.PACKAGE_ARTIFACT_DIR }} \
-          --dest-dir ${{ env.DOCKER_ARTIFACT_DIR }} \
-          --generate-sbom ${{ env.GENERATE_SBOM }}
+          --src-dir $PACKAGE_ARTIFACT_DIR \
+          --dest-dir $DOCKER_ARTIFACT_DIR \
+          --generate-sbom $GENERATE_SBOM
 
       - name: "Generate Build SBOM"
-        if: ${{ env.GENERATE_SBOM == 'true'  && env.FOR_DOCKER == 'false' }}
+        if: ${{ env.GENERATE_SBOM == 'true'  && env.FOR_DOCKER != 'true' }}
         run: |
           ./tools/sbom/build-sbom.sh
 
@@ -235,26 +240,26 @@ jobs:
           commit="$(git rev-parse HEAD | cut -c1-12)"
 
           # set the artifact directory containing the file we want to rename
-          if [ "${{ env.FOR_DOCKER }}" == "true" ]; then
-            artifact_path="${{ env.DOCKER_ARTIFACT_DIR }}"
+          if [ "$FOR_DOCKER" == "true" ]; then
+            artifact_path="$DOCKER_ARTIFACT_DIR"
           else
-            artifact_path="${{ env.PACKAGE_ARTIFACT_DIR }}"
+            artifact_path="$PACKAGE_ARTIFACT_DIR"
           fi
 
           # find the existing file name
           old_name="$(ls -1 $artifact_path/memgraph* 2>/dev/null | head -n 1)"
 
           # determine new name
-          if [ "${{ env.FOR_DOCKER }}" == "true" ]; then
+          if [ "$FOR_DOCKER" == "true" ]; then
             new_name="memgraph-${tag}_pr${pr}_${commit}"
-            if [[ "${{ inputs.build_type }}" == 'RelWithDebInfo' ]]; then
+            if [[ "$BUILD_TYPE" == 'RelWithDebInfo' ]]; then
               new_name="${new_name}-relwithdebinfo"
             fi
             new_name="${new_name}-docker.tar.gz"
           elif [[ "$INPUT_OS" == *"debian"* || "$INPUT_OS" == *"ubuntu"* ]]; then
-            new_name="memgraph_${tag}+pr${pr}~${commit}-1_${{ inputs.arch }}64.deb"
+            new_name="memgraph_${tag}+pr${pr}~${commit}-1_${ARCH}64.deb"
           elif [[ "$INPUT_OS" == *"centos"* || "$INPUT_OS" == *"fedora"* || "$INPUT_OS" == *"rocky"* ]]; then
-            if [[ "${{ inputs.arch }}" == "amd" ]]; then
+            if [[ "$ARCH" == "amd" ]]; then
               arch_str="x86_64"
             else
               arch_str="aarch64"
@@ -275,7 +280,7 @@ jobs:
       - name: "Upload to S3"
         if: ${{ inputs.push_to_s3 == 'true' }}
         run:
-          aws s3 sync $SOURCE_DIR s3://${{ inputs.s3_bucket }}/$DEST_DIR
+          aws s3 sync $SOURCE_DIR s3://${S3_BUCKET}/$DEST_DIR
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
