undo s3 changes

diff --git a/.github/workflows/reusable_package.yaml b/.github/workflows/reusable_package.yaml
--- a/.github/workflows/reusable_package.yaml
+++ b/.github/workflows/reusable_package.yaml
@@ -31,14 +31,18 @@ on:
         type: string
         description: "Should the final package be pushed to an S3 bucket. Default value is false."
         default: false
-      s3:
+      s3_bucket:
         type: string
-        description: 'A JSON string containing S3 configuration with keys "bucket", "region", and "dest_dir".'
-        default: '{"bucket": "", "region": "eu-west-1", "dest_dir": ""}'
-      test_result:
+        description: "Name of the target S3 bucket."
+        default: ''
+      s3_region:
         type: string
-        description: "Results of testing"
-        default: ""
+        description: "Region for the target S3 bucket."
+        default: eu-west-1
+      s3_dest_dir:
+        type: string
+        description: "Target dir path in S3 bucket."
+        default: ''
 
 jobs:
   PackageAndUpload:
@@ -47,28 +51,18 @@ jobs:
     env:
       mgdeps_cache_host: "${{ inputs.arch == 'arm' && 'false' || 'mgdeps-cache' }}" # Required because strange is not connected to memgraph openVPN
     steps:
-      - name: Parse S3 input into environment variables
-        run: |
-          echo "S3_BUCKET=${{ fromJson(inputs.s3).bucket }}" >> $GITHUB_ENV
-          echo "S3_REGION=${{ fromJson(inputs.s3).region }}" >> $GITHUB_ENV
-          S3_DEST_DIR="${{ fromJson(inputs.s3).dest_dir }}"
-          if [ "$S3_DEST_DIR" == "daily-build" ]; then
-            S3_DEST_DIR="$S3_DEST_DIR/$(date +%Y%m%d)"
-          fi
-          echo "S3_DEST_DIR=$S3_DEST_DIR" >> $GITHUB_ENV
-
       - name: "Validate S3 dest dir for official package"
-        if: ${{ inputs.push_to_s3 == 'true' && env.S3_BUCKET == 'download.memgraph.com' }}
+        if: ${{ inputs.push_to_s3 == 'true' && inputs.s3_bucket == 'download.memgraph.com' }}
         run: |
           if [[ "${{ inputs.build_type }}" == 'RelWithDebInfo' ]]; then
             echo -e "Error: You are pushing a RelWithDebInfo build to 'download.memgraph.com'."
             exit 1
           fi
-          if ! [[ "${{ env.S3_DEST_DIR }}" =~ memgraph/v[0-9]\.[0-9]+\.[0-9]+$ ]]; then
-            echo -e "Error: ${{ env.S3_DEST_DIR }} is not a valid official format. When pushing to 'download.memgraph.com' the dest dir has to match format 'memgraph/vX.Y.Z'!"
+          if ! [[ "${{ inputs.s3_dest_dir }}" =~ memgraph/v[0-9]\.[0-9]+\.[0-9]+$ ]]; then
+            echo -e "Error: ${{ inputs.s3_dest_dir }} is not a valid official format. When pushing to 'download.memgraph.com' the dest dir has to match format 'memgraph/vX.Y.Z'!"
             exit 1
           fi
-          echo -e "Passed: Dest dir ${{ env.S3_DEST_DIR }} has a valid official format."
+          echo -e "Passed: Dest dir ${{ inputs.s3_dest_dir }} has a valid official format."
 
       - name: "Set up repository"
         uses: actions/checkout@v4
@@ -184,13 +178,13 @@ jobs:
       - name: "Upload to S3"
         if: ${{ inputs.push_to_s3 == 'true' }}
         run:
-          aws s3 sync $SOURCE_DIR s3://${{ env.S3_BUCKET }}/$DEST_DIR
+          aws s3 sync $SOURCE_DIR s3://${{ inputs.s3_bucket }}/$DEST_DIR
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
-          AWS_REGION: ${{ env.S3_REGION }}
+          AWS_REGION: ${{ inputs.s3_region }}
           SOURCE_DIR: ${{ env.FOR_DOCKER == 'true' && env.DOCKER_ARTIFACT_DIR || env.PACKAGE_ARTIFACT_DIR }}
-          DEST_DIR: "${{ env.S3_DEST_DIR }}/${{ env.ARTIFACT_NAME }}/"
+          DEST_DIR: "${{ inputs.s3_dest_dir }}/${{ env.ARTIFACT_NAME }}/"
 
 
       - name: Get Package Name
@@ -215,9 +209,9 @@ jobs:
           echo "PACKAGE_URL=${PACKAGE_URL}" >> $GITHUB_OUTPUT
           echo "Package URL: ${PACKAGE_URL}"
         env:
-          S3_BUCKET: ${{ env.S3_BUCKET }}
-          S3_REGION: ${{ env.S3_REGION }}
-          S3_DEST_DIR: ${{ env.S3_DEST_DIR }}
+          S3_BUCKET: ${{ inputs.s3_bucket }}
+          S3_REGION: ${{ inputs.s3_region }}
+          S3_DEST_DIR: ${{ inputs.s3_dest_dir }}
           ARTIFACT_NAME: ${{ env.ARTIFACT_NAME }}
           PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
 
